### ISSUE TITLE
NPE when no Play services available on the device

### ISSUE THREAD

**Issue by mack369** [beaconinside/beaconinside-android-sdk#1]
I'm using beaconinside-sdk-playservices-2.5.1.aar version of the sdk. 

Whenever I try to run the app on the device without Google Play Services, I get the following exception:

> 12-19 08:49:46.302 3253-3273/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
>                                                  Process: com.esprit.espritapp.debug, PID: 3253
>                                                  java.lang.RuntimeException: An error occured while executing doInBackground()
>                                                      at android.os.AsyncTask$3.done(AsyncTask.java:304)
>                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                      at java.lang.Thread.run(Thread.java:818)
>                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.ads.identifier.AdvertisingIdClient$Info.isLimitAdTrackingEnabled()' on a null object reference
>                                                      at com.beaconinside.androidsdk.c.a(Unknown Source)
>                                                      at com.beaconinside.androidsdk.b.a(Unknown Source)
>                                                      at com.beaconinside.androidsdk.b.doInBackground(Unknown Source)
>                                                      at android.os.AsyncTask$2.call(AsyncTask.java:292)
>                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
>                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
>                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
>                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by bashtian** [comment]
Thank you for the report, this is fixed internally and will be in the next release of the SDK.

**Comment by bashtian** [comment]
Fixed in 2.7.2
