### ISSUE TITLE
What is the recommended way to receive messages in the background?

### ISSUE THREAD

**Issue by mattat11** [beaconinside/beaconinside-android-sdk#2]
Hi,

The service you provided is using the [LocalBroadcastManager ](https://developer.android.com/reference/android/support/v4/content/LocalBroadcastManager.html) to send notifications to the app, where I want to receive those.
Unfortunately, LocalBroadcastManager isn't really a usual BroadcastReceiver, so instead of registering the BroadcastReceiver programatically with `LocalBroadcastManager.getInstance(this).registerReceiver(mReceiver, mFilter);` there isn't a way to declare any receiver statically in the android manifest, which can receive messages from a LocalBroadcastManager. (There are several posts on stackoverflow about that: [here](http://stackoverflow.com/questions/23364668/register-a-local-broadcastreceiver-in-androidmanifest-xml))

So, the problem is that if I want to receive messages from the BeaconService in the background of my app (or while the app is closed) I have to keep running another service, which registers a receiver with LocalBroadcastManager. In your sample code, you have only provided code on how to receive the messages in a currently running Activity, but because of the fact, that your BeaconService keeps running in background, it implies that there must be proper way how to receive those messages sent in background, too. Furthermore, your BeaconService is obviously using a timer or has some triggers on how to wake up (what you've described in the "Behavior" section), so e.g. it would make sense to extend the BeaconService, so that the developer doesn't have to take care of keeping another service awake while the BeaconService sends the messages.

Currently I'm using the approach that I'll keep a service running in background, which registers the LocalBroadcastManager, but please keep in mind that this is not the best solution due to many reasons. Keeping another service alive may have further resource costs, the service might also sometimes get killed even though it is explicitly marked as sticky. Furthermore, the new upcoming Android Version "O" is going to limit background services as well (https://www.theverge.com/2017/3/21/14988222/android-o-app-background-run). When I use a another service, I also somehow have to take care of starting it after a reboot, etc.

I appreciate any kind of help and possible approaches.

BR,

**Comment by bashtian** [comment]
The next version of the SDK will have have normal broadcast intents which can be used with a BroadcastReceiver in the manifest. With this SDK the additional service is not needed anymore. 

The SDK will be released in the next weeks, I will update the issue when it's available.

**Comment by bashtian** [comment]
The new SDK is now available  https://github.com/beaconinside/beaconinside-android-sdk/releases/tag/v2.8.1
